export const CHANGE_PUZZLE_POSITION = "CHANGE_PUZZLE_POSITION";

export const SNAKE_MOVE_RIGHT = "SNAKE_MOVE_RIGHT";
export const SNAKE_MOVE_LEFT = "SNAKE_MOVE_LEFT";
export const SNAKE_MOVE_TOP = "SNAKE_MOVE_TOP";
export const SNAKE_MOVE_BOTTOM = "SNAKE_MOVE_BOTTOM";

export const OPEN_CLOSE_CARD = "OPEN_CLOSE_CARD";
export const START_NEW_GAME_PAIR = "START_NEW_GAME_PAIR";
